# Spring Application
spring.application.name=merchant-onboarding-service

# Server 
server.port = 8080

# ===== DataSource =====
spring.datasource.url=jdbc:postgresql://localhost:5432/merchant_onboard_db
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Internationalization Configuration
spring.messages.basename=error-messages